### ISSUE TITLE
Remove white spaces between literals (reserved words)

### ISSUE THREAD

**Issue by JimmyRowland** [JimmyRowland/CalendarDSL#8]
Tokenizer should turn
LITERAL LITERAL
into [LITERAL, LITERAL] not [LITERAL,"white space",LITERAL]

**Comment by aid848** [comment]
Whitespace seems to be put into tokens list in the tokenizer

**Comment by aid848** [comment]
Seem to be on machines that use CRLF endings instead of just LF.
Fixed on dev branch but needs to be tested.

**Comment by aid848** [comment]
Still has whitespace problem some of the time for groupTests1

**Comment by aid848** [comment]
I wrote a new method that fixes it for groups in my branch
